### ISSUE TITLE
El proceso de adopción no funciona correctamente

### ISSUE THREAD

**Issue by arturodaw** [MariaAdel-22/proyectoIpets#14]
El proceso de adopción no funciona correctamente.

Repro:
1. Usuario se loguea
2. Elige un animal (icono corazón).
3. Servicio a domicilio
4. Adoptar

La aplicación no responde.

![image](https://user-images.githubusercontent.com/14854340/84030134-cd6d4b00-a993-11ea-8d20-72a832479f75.png)

**Comment by arturodaw** [comment]
Sigue sin funcionar.

**Comment by MariaAdel-22** [comment]
Recién cambié la estructura del proceso de adopción y lo probé,creo que ya si funciona.
