### ISSUE TITLE
Errores en el proceso de registro

### ISSUE THREAD

**Issue by arturodaw** [MariaAdel-22/proyectoIpets#15]
El proceso de registro no funciona. 
Tras haber rellenado todos los campos (imagen de usuario incluida), al pulsar el botón de "Registrarme" no ocurre ninguna acción.

El patrón al que se obliga al usuario es confuso y poco práctico:
![image](https://user-images.githubusercontent.com/14854340/84753704-a0d2b800-afbf-11ea-83d7-4733b2b30ea1.png)

La contraseña no se debe mostrar y la palabra "_contrasenia_" no existe.
![image](https://user-images.githubusercontent.com/14854340/84753914-ea230780-afbf-11ea-92e4-ec153e7c6e92.png)

**Comment by MariaAdel-22** [comment]
Ya está resuelto éste error y añadido la encriptación a la hora de registrarse.

**Comment by arturodaw** [comment]
Añado lo siguiente: fallo de usabilidad (seguro que conoces opciones mejores para una respuesta del tipo `sí / no`) ;)

![image](https://user-images.githubusercontent.com/14854340/85056987-6b38f500-b1a0-11ea-983c-715a604c5824.png)

**Comment by arturodaw** [comment]
Añado: el patrón en el campo de dirección sigue activo. 
Lo mejor es quitarlo o poner un patrón mucho más sencillo.

**Comment by arturodaw** [comment]
> Ya está resuelto éste error y añadido la encriptación a la hora de registrarse.

**El proceso de registro no funciona correctamente.**
Tras rellenar todos los campos y crear un nuevo usuario (he comprobado que está en la BD), intento entrar en la aplicación y no me lo permite.

![image](https://user-images.githubusercontent.com/14854340/85057729-6cb6ed00-b1a1-11ea-9fcc-9dc59a727c96.png)
